services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      # Override container .env with production values
      - ENVIRONMENT=production
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=false
      - LOG_LEVEL=INFO
      
      # Security (override with secure values)
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-in-production-please}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      - ALGORITHM=${ALGORITHM:-HS256}
      
      # Database
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./app.db}
      - DATABASE_ECHO=${DATABASE_ECHO:-false}
      
      # Redis (optional)
      - REDIS_URL=${REDIS_URL:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      
      # OpenTelemetry
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-fastapi-starter}
      - OTEL_SERVICE_VERSION=${OTEL_SERVICE_VERSION:-1.0.0}
      
      # External services (optional)
      - EXTERNAL_API_URL=${EXTERNAL_API_URL:-}
      - EXTERNAL_API_KEY=${EXTERNAL_API_KEY:-}
    depends_on:
      - jaeger
      - otel-collector
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC (for otel-collector)
      - "4318:4318"     # OTLP HTTP (for otel-collector)
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./scripts/opentelemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "14317:4317"   # OTLP gRPC receiver
      - "14318:4318"   # OTLP HTTP receiver
      - "13133:13133"  # Health check endpoint (accessible from host)
    depends_on:
      jaeger:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  default:
    name: fastapi-starter-network
