version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"  # Map host 8000 to container 8080
    environment:
      # Application settings
      - ENVIRONMENT=production
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8080
      - RELOAD=false
      - LOG_LEVEL=INFO
      
      # Security
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-in-production-please}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      - ALGORITHM=${ALGORITHM:-HS256}
      
      # Database
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./app.db}
      - DATABASE_ECHO=${DATABASE_ECHO:-false}
      
      # OpenTelemetry (disabled for simple setup)
      - OTEL_EXPORTER_OTLP_ENDPOINT=
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-fastapi-backend}
      - OTEL_SERVICE_VERSION=${OTEL_SERVICE_VERSION:-1.0.0}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - fastapi-backend-network

networks:
  fastapi-backend-network:
    driver: bridge
