receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  # Memory limiter to prevent OOM
  memory_limiter:
    limit_mib: 128
    check_interval: 1s

exporters:
  # Use OTLP exporter to send to Jaeger
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

extensions:
  # Health check extension
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
  
  telemetry:
    logs:
      level: info
    metrics:
      level: basic
